### ISSUE TITLE
[Feature Request]: prebundle rspack config file by rspack itself for better config extensions support

### ISSUE THREAD

**Issue by fi3ework** [web-infra-dev/rspack#2237]
### What problem does this feature solve?

Support multiple config file extensions, such as `mjs` `ts` `cjs` `mts` `cts`, especially `ts` for better intellisense and type check.

### What does the proposed API of configuration look like?

Utilize rspack itself to pre-bundle the config file. The bundling should have the following features:

1. A default unmodifiable sane nodejs lib config
2. Externalize dependencies in node_modules
3. Support both ESM and CJS output
4. Hijacking `require.extensions` to load CJS and use temp file (before `--loader` landed) for ESM.

**Comment by wernerbihl** [comment]
I'm particularly interested in support for .cjs config because all my projects have "type": "module" in package.json. But when changing the sample provided "rspack.config.js" (with no requires or imports) to "rspack.config.cjs", then I get the following:

`TypeError: Cannot read properties of undefined (reading 'import')
    at getNormalizedEntryStatic (/var/www/rspack-project/node_modules/@rspack/core/src/config/normalization.ts:202:33)
    at getNormalizedRspackOptions (/var/www/rspack-project/node_modules/@rspack/core/src/config/normalization.ts:32:7)
    at createCompiler (/var/www/rspack-project/node_modules/@rspack/core/src/rspack.ts:55:44)
    at create (/var/www/rspack-project/node_modules/@rspack/core/src/rspack.ts:141:20)
    at rspack (/var/www/rspack-project/node_modules/@rspack/core/src/rspack.ts:165:31)
    at RspackCLI.createCompiler (/var/www/rspack-project/node_modules/@rspack/cli/src/rspack-cli.ts:49:26)
    at Object.handler (/var/www/rspack-project/node_modules/@rspack/cli/src/commands/build.ts:94:22)
`

**Comment by hardfist** [comment]
@wernerbihl .cjs is supported

**Comment by hardfist** [comment]
@fi3ework  prebundle may meet lots of issue like https://github.com/web-infra-dev/modern.js/issues/3338,especialy when used in monorepo, if we bundle code in other package it will cause the bundled config can't find the its dependencies, so we think transformer is less prone

**Comment by fi3ework** [comment]
Prebundling could externalize bare imports, which would skip libraries in a monorepo, but still will meet ﻿`type: module/commonjs` issues.

**Comment by hardfist** [comment]
if config a in packageA use source b in packageB which has dependency c, when we do prebundle it will cause b is bundled in bundled_a file which is in packageB, then we do resolve dependency in bundle_a it will resolve failed because lies in packageB's node_modules other than packageA's node_modules
```
packageA
  config_a 
packageB
  b -> require('c')
  node_modules/c
```
when bundled config_a it will becomes
```
packageA
  config_a
  bundled_config_a -> require('c')
packageB
  b
  node_modules/c
```
then require('c') will failed because packageA doesn't have c in node_modules

**Comment by fi3ework** [comment]
Yes, it will. I was trying to say that making bare import externalized will keep resolving `'c'` from B, which is how Vite behaves now. But using a transformer could be a more powerful solution.

**Comment by hardfist** [comment]
> Yes, it will. I was trying to say that making bare import externalized will keep resolving `'c'` from B, which is how Vite behaves now. But that will not work for loading ts in other monorepo package. Using a transformer could be a more powerful solution.

then we will stick to transformer solution for now and may use rspack itself to transform config one day.

**Comment by hardfist** [comment]
closed as not planned
