### ISSUE TITLE
v0.1.12 - `[ext]` no longer resolved/recognized

### ISSUE THREAD

**Issue by mandarini** [web-infra-dev/rspack#3270]
### System Info

```
  System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 35.26 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.15.0/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Edge: 111.0.1661.51
    Firefox: 102.0.1
    Safari: 16.0
  npmPackages:
    @rspack/cli: latest => 0.1.12 
```

### Details

Starting `v0.1.12` [the `[ext]` of file context](https://www.rspack.dev/config/output.html#file-context) is no longer replaced/recognized.

### Reproduce link

https://github.com/mandarini/rspack-react-app

### Reproduce Steps

1. `git clone git@github.com:mandarini/rspack-react-app.git`
2. `cd rspack-react-app`
3. `npm i`
4. `npm run build`
5. observe contents of `dist`:
```
index.html
main.5ac7aa5c.5ac7aa5c[ext].map
main.5ac7aa5c[ext]
main.c94f583d.c94f583d[ext].map
main.c94f583d[ext]
```

**Comment by hardfist** [comment]
sorry this is indeed a **breaking change** which should be shipped on 0.2.0, but support for `[ext]` in output.filename is actually a **bug**, if you try it in webpack, webpack will also keep `[ext]`, so when we implement realContentHash we align this behavior with webpack.
sorry to bother you @alexander-akait, do you know why webpack wouldn't support [ext] in output.filename?

**Comment by mandarini** [comment]
What would you suggest as an alternative, where could I use `[ext]`instead? Should the docs (https://www.rspack.dev/config/output.html#file-context) be updated?

**Comment by ahabhgk** [comment]
We definitely need to update our docs, but before we update the docs, here are some tips maybe helpful:

- `filename: "[name].[contenthash].js"` is for js file (and I suggest use this as an alternative)
- `chunkFilename: "[name].[contenthash].js"` is for js async chunk file
- `cssFilename: "[name].[contenthash].css"` is for css file
- `cssChunkFilename: "[name].[contenthash].css"` is for css async chunk file
- `assetModuleFilename: "[name].[contenthash][ext]"` is for asset file, since there are different asset with different extensions, you can use `[ext]` in this options, basic only asset related filename options needs `[ext]`

**Comment by alexander-akait** [comment]
> sorry to bother you @alexander-akait, do you know why webpack wouldn't support [ext] in output.filename?

@hardfist 

because it didn't really make sense, there are only three possible things - `.js`/`.mjs` and `.cjs`, `.js` and `.cjs` is the same when you don't have `type: "module"`, if you don't have `type: "module"` and want to emit ESM we use `.mjs`, if you have `type: "module"`, you can use `.mjs`. 

Also for example you can consume `my-entry.js` and want to output ESM (and don't have `type: "module"`), in such case we will use `.mjs`, so if you i will use `[ext]` and so use `.js` it will be invalid because you will have ESM in `.js` file.

In theory we can implement `[ext]` supporting `output.filename`, but:
- it can lead to problems with mixing CommonJS and ESM in one project (I written about it above)
- You can have `my-entry.ts`, so what extension we should use? We need analize tsconfig.json and undestand what output will be used - ESM our CommonJs/etc, it is really tricky (and I think out of scope a bundler), you even have `my-entry.unknown` (and have any things there which will generate JavaScript)
- What is the real use case?

**Comment by hyf0** [comment]
This alignment is introduced at #3143. I would consider the change a bug fix rather than a behavior change.

But we should address this in the release note and give proper guidance for adopting the fix in the userland.

**Comment by hardfist** [comment]
@mandarini do you think we should revert this change and introduced in 0.2.0 or leave as it is

**Comment by mandarini** [comment]
We were using `[ext]` in our Nx-Rspack integration, and we had the version point to `~0.1.0`, so that's why it broke our integration. Yesterday I pushed a PR that locked our version to `0.1.11`. I don't know the timeline for 0.2.0, but in any case, I will update our code according to your suggestions above! :D 

That being said, I don't know what would be best for rspack. I mean, if someone is using `[ext]` and they had their version point to `~0.1.0`, then their code will break, since this seems to be to be a breaking change, and also not consistent to the current documentation. I understand that in essence it's more of a bug fix, so I am just explaining our point of view, which may as well be wrong. 😅

**Comment by hardfist** [comment]
@mandarini 0.2.0 will be released soon, and I think we will add check for filename contains `[ext]`, so when people use `[ext]` in filename we will throw error or warning to avoid silent failure

**Comment by mandarini** [comment]
Oh perfect!! Thank you very much @hardfist ! :D
