### ISSUE TITLE
[BUG]sourceMapFilename Conflict multiple assets

### ISSUE THREAD

**Issue by B1anker** [web-infra-dev/rspack#3313]
### System Info

System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 194.64 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.6.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 103.0.2
    Safari: 16.4

### Details

![c51fc219-4d0c-4959-9e50-5f20ed0b90ce](https://github.com/web-infra-dev/rspack/assets/17514962/1359d799-3b00-46f5-9e7b-17a69556c157)

![fabb3a37-b188-4467-b541-db3f64d245ce](https://github.com/web-infra-dev/rspack/assets/17514962/e5f826f8-6354-4415-8125-16721ef46a63)

### Reproduce link

https://github.com/B1anker/multiple-assets

### Reproduce Steps

1. yarn install
2. yarn build

**Comment by faga295** [comment]
Seems webpack also has this problem

**Comment by alexander-akait** [comment]
@faga295 Sorry, can you provide an example of the problem? I tried to reproduce, but no luck

**Comment by faga295** [comment]
https://github.com/faga295/rspack-reproduce/tree/sourcemap_multiple_emit reproduce step: pnpm build:webpack

**Comment by alexander-akait** [comment]
@faga295 I see, that is the intresting issue, when you have child compilation and use default entry (i.e. just pass entry) you will have two files:
- main.css
- main.js

Using `sourceMapFilename: "sourcemap/[name][ext].map"` is not good idea, because you will have `sourcemp/main.map` file for JS and CSS, that is why webpack reports about it, default value `sourceMapFilename: "[file].map[query]"` (file already contains an extensions).

Even more look at dist, you have `main.map`, it is not good idea to have just a `map` extension, I would recommend to always have an original extension, i.e. `file.js.map`/`file.css.map`/`file.something.map`.

Under the hood in plugins you can have any numbers of child compilations, we can't control it.

Perhaps we could write a warning about this, but in the real world, I have seen similar uses in various exotic situations, so it will be a bad DX for them, maybe the best solution is improve documentation and write `Always use [ext] in sourceMapFilename, unless you understand why you don't need it`
