### ISSUE TITLE
Make externalsPresets.node obey externalsType option

### ISSUE THREAD

**Issue by blinkzz** [web-infra-dev/rspack#3446]
### What problem does this feature solve?

Right now `node_target_plugin` has `node-commonjs` value hardcoded as externals type (same as Webpack), but for better ESM compatibility it would be nice if it inherited value of `externalsType` configuration option. This way all nodejs builtins can be easily excluded from bundling and will be imported at runtime natively via ESMs import syntax

### What does the proposed API of configuration look like?

```
externalsPresets: { node: true },
externalsType: 'module'
```

**Comment by zackarychapple** [comment]
I wonder if this is a change @TheLarkInn and @alexander-akait will also be making as part of the ESM support in webpack being tracked in [webpack/17121](https://github.com/webpack/webpack/issues/17121)

**Comment by blinkzz** [comment]
Do we really need to wait until it lands in Webpack before something like this can be implemented?

**Comment by hardfist** [comment]
> Do we really need to wait until it lands in Webpack before something like this can be implemented?

if it's confirmed as a bug we're willing to fix it both in rspack and webpack, but we may need to discuss with webpack team about the api design context and make sure it's a bug before fixing it.

**Comment by alexander-akait** [comment]
@blinkzz technically you are right, but not all `externalsType` values supported for Node.js, I think we should use logic:
```
new ExternalsPlugin(isModule ? "module" : "node-commonjs", builtins).apply(compiler);
``` 

Just intresting - why you want to use another value? I would just like to understand that there are no bugs or something else

**Comment by blinkzz** [comment]
@alexander-akait, just for consistency, since `externalsType` already controls user-defined packages in `externals`, so why not use it for presets too, it’s very unlikely that somebody will make a mistake here by choosing wrong type for their environment

**Comment by alexander-akait** [comment]
@blinkzz 

> it’s very unlikely that somebody will make a mistake here by choosing wrong type for their environment

You can take my word for it, they did it :smile: so I think it's better to limit "module" and "node-commonjs"`, both can be used.

Here is another problem, there is a situation - some Node.js modules doesn't work with ESM. Example:
```js
import zlib from 'node:zlib';

console.log(zlib)
```

and

```
const zlib = require('node:zlib'); 

console.log(zlib)
```

You can found more them, and to avoid this ploblem we are using `node-commonjs`, because it always works. Yes, we can check a type of dependency and generate output based on it (i.e. use `import` when `import` was used), but not sure it is really worth prioritizing...

**Comment by alexander-akait** [comment]
So changing it right now can break build for some developers... it is a little bit tricky to implement this right, we need:
- wait until Node.js will have support for all built-in modules in ESM (if it will be not, we need to have two lists)
- maybe we will need `browserslist` because some modules were unavaliable in ESM and now they are avaliable
- analize original dependency (how developer imported it and it should be `import ... from ...;`)

**Comment by hardfist** [comment]
> @blinkzz
> 
> > it’s very unlikely that somebody will make a mistake here by choosing wrong type for their environment
> 
> You can take my word for it, they did it 😄 so I think it's better to limit "module" and "node-commonjs"`, both can be used.
> 
> Here is another problem, there is a situation - some Node.js modules don't work with ESM. Example:
> 
> ```js
> import zlib from 'node:zlib';
> 
> console.log(zlib)
> ```
> 
> and
> 
> ```js
> const zlib = require('node:zlib'); 
> 
> console.log(zlib)
> ```
> 


that is a good catch，nodejs changes esm behaviour a lot in different version，which makes esm harder to work on all supported nodejs version

**Comment by alexander-akait** [comment]
@hardfist Yeah, therefore, purely theoretically, this is a solvable problem, but it will take time and you will have to maintain a map of modules and versions

**Comment by hardfist** [comment]
close as it's same as webpack
