### ISSUE TITLE
remove sourcemap in dist when publish

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#3515]
https://www.npmjs.com/package/@rspack/core?activeTab=code
we shipped sourcemap without shipping source, and it seems unnecessary ship source and sourcemap in the dist(which will cause npm download slow)
so it would be better we just remove sourcemap when publish(but we need sourcemap in development for better debug experience)

**Comment by hardfist** [comment]
we may need two `tsconfig.json`, `tsconfig.build.json` for build and publish(without sourcemap) and  `tsconfig.json` for local development(with sourcemap).

**Comment by RussellCanfield** [comment]
@hardfist - I would be interested in contributing to this issue. I would likely use the existing "prepare" script in rspack/core, and run a clean/build using another tsconfig.build.json (or tsconfig.lib.json) with source maps disabled.

Assuming we wanted the build to be part of prepare, or just enhance the existing build script since there is already a dev script that performs a watch on the default tsconfig.json.

**Comment by hardfist** [comment]
> @hardfist - I would be interested in contributing to this issue. I would likely use the existing "prepare" script in rspack/core, and run a clean/build using another tsconfig.build.json (or tsconfig.lib.json) with source maps disabled.
> 
> Assuming we wanted the build to be part of prepare, or just enhance the existing build script since there is already a dev script that performs a watch on the default tsconfig.json.

yeah. that is what we want
