### ISSUE TITLE
Matching jsx syntax in vue2

### ISSUE THREAD

**Issue by Aszzo** [web-infra-dev/rspack#4003]
### System Info

System:
    OS: macOS 13.5
    CPU: (10) x64 Apple M2 Pro
    Memory: 295.67 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 14.18.3 - ~/.nvm/versions/node/v14.18.3/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.3/bin/npm
  Browsers:
    Chrome: 116.0.5845.96
    Safari: 16.6
  npmPackages:
    @rspack/cli: ^0.2.11 => 0.2.11 

### Details

在 vue2 中处理 jsx 的语法时，对于 vue 文件中的 `<script lang="jsx">` 块会有匹配不到的情况（大概十次中出现2次），我怀疑是 Rspack 异步loader机制的产生的，但是我未找到明确的原因

When dealing with jsx syntax in vue2, there are failures to match `<script lang="jsx">` blocks in vue files (about 2 out of 10 times), which I suspect is due to Rspack's asynchronous loader mechanism, but I haven't found a clear reason for this

```
// rspack.config.js

const { VueLoaderPlugin } = require("vue-loader");

/** @type {import('@rspack/cli').Configuration} */
const config = {
	context: __dirname,
	entry: {
		main: "./src/main.js"
	},
	builtins: {
		html: [
			{
				template: "./index.html"
			}
		]
	},
	devServer: {
		historyApiFallback: true
	},
	devtool: false,
	plugins: [new VueLoaderPlugin()],
	resolve: {
		extensions: ['.js', '.vue', '.json', '.wasm'],
		alias: {
			vue$: 'vue/dist/vue.runtime.esm.js'
		}
	},
	module: {
		rules: [
			{
				test: /\.vue$/,
				loader: 'vue-loader'
			},
			{
				test: /\.(js|jsx)$/,
				use: [{
					loader: 'babel-loader',
					options: {
						presets: ['@vue/babel-preset-jsx']
					}
				}],
				exclude: /node_modules/
			},
			{
				test: /\.less$/,
				use: ["vue-style-loader", "css-loader", "less-loader"],
				type: "javascript/auto"
			},
			{
				test: /\.css$/,
				use: ["vue-style-loader", "css-loader"],
				type: "javascript/auto"
			},
			{
				test: /\.svg$/,
				type: "asset/resource"
			}
		]
	}
};
module.exports = config;
```

### Reproduce link
https://github.com/Aszzo/rspack-vue2-jsx

### Reproduce Steps
- `npm i`
- `npm run dev`

大概10次会有2-3次 `JavaScript parsing error` 的情况
About 2-3 times out of 10, there will be a `JavaScript parsing error`.

<img width="986" alt="image" src="https://github.com/web-infra-dev/rspack/assets/22289676/e0e739ac-d2cd-4822-a711-773802a41612">

**Comment by h-a-n-a** [comment]
Please attach a reproduction repo

**Comment by Aszzo** [comment]
> Please attach a reproduction repo
done

**Comment by Aszzo** [comment]
> Please attach a reproduction repo

done @h-a-n-a

**Comment by h-a-n-a** [comment]
> > Please attach a reproduction repo
> 
> done @h-a-n-a

@Aszzo I will take a look ASAP.

**Comment by h-a-n-a** [comment]
The underlying cause of this instability is related to Rspack's multi-threaded version and vue's rule matching logic.

The code snippet in the vue-loader shows this problem:
https://github.com/vuejs/vue-loader/blob/c9a341d1e7bd97c2399c048e2772b2b064977bd5/lib/plugin-webpack5.js#L250-L279
In order to create a custom matching logic with files, vue-loader is trying to get `resourcePath` and `resourceQuery` together in two steps. In webpack, due to JavaScript engine is being running on a single-threaded version, this does not have any problems. However, in Rspack, Rust is running on multi-threaded version, however this rule can be matched with multiple files, which results in the `resource` function (getting `resourcePath`) being called by two modules before `resourceQuery` is called. This swaps the old `currentResource`, causing the `resourceQuery` function not matched by mistake, which results in the rule is not getting matched.

**Comment by h-a-n-a** [comment]
Since this is not an issue with Rspack, the follow-ups will be tracked in https://github.com/rspack-contrib/rspack-vue-loader/issues/2 and this issue will be closed.

**Comment by h-a-n-a** [comment]
I decide to improve the compatibility on Rspack, let’s reopen this right away.

**Comment by h-a-n-a** [comment]
@Aszzo 最新版本在 Rspack 上兜了这个问题，可以试试 0.3.1-canary-efd2bf0-20230906032925.
