### ISSUE TITLE
need an option to control whether enable or disable project reference

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4211]
we need an option to control whether enable or disable project reference, so I suggest following options
```js
module.exports = {
resolve: {
  tsconfig: {
    configFile: './tsconfig.json',
    references: ['./a/tsconfig.json', './b.tsconfig.json'] | 'auto' | undefined 
    // undefined or no value means don't enable project reference
    // 'auto' means enable auto project reference
    // ['./a/tsconfig.json','./b/tsconfig.json'] means manual config project reference
 }
}
}
```
and current tsConfigPath is just syntax sugar
```js
{
  resolve: { 
   tsConfigPath: './tsconfig.json'
 }
}
```
is syntax sugar of the following and will be deprecated in the future
```js
{
 resolve: { 
   tsconfig:{
     configFile: './tsconfig'
    }
}
}
```

_Originally posted by @hardfist in https://github.com/web-infra-dev/rspack/issues/4192#issuecomment-1719253012_

**Comment by chenjiahan** [comment]
Modern.js provides a [source code build mode](https://modernjs.dev/builder/en/guide/advanced/source-build.html), it allows developers to directly reference the source code of other sub-projects within the monorepo for development.

When using webpack, Modern.js uses the references option of [tsconfig-paths-webpack-plugin](https://github.com/dividab/tsconfig-paths-webpack-plugin#readme) to support TypeScript project references, so that the use of aliases in the sub-project works correctly.

And when using Rspack, we want to take the same behavior, so it would be nice if Rspack can provide an option to control the references.
