### ISSUE TITLE
vue3 迁移 pinia 引入报错

### ISSUE THREAD

**Issue by JdesEva** [web-infra-dev/rspack#4394]
### System Info

  System:
    OS: macOS 13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 3.10 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 118.0.5993.88
    Safari: 17.0

### Details

![image](https://github.com/web-infra-dev/rspack/assets/37232561/1f022d09-fa09-42d2-91bf-ece38c401c81)

引入pinia 都会报这个错误 

<img width="531" alt="image" src="https://github.com/web-infra-dev/rspack/assets/37232561/8d8aef5a-62e8-4808-93b5-e465120fe0b8">
统一导出标准 pinia 模块 
<img width="622" alt="image" src="https://github.com/web-infra-dev/rspack/assets/37232561/d0183576-d4ca-4811-bc31-487b81f5d8ea">
按需引入即报错

### Reproduce Steps

package.json

{
  "name": "rspack-vue-starter",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "main": "index.js",
  "scripts": {
    "dev": "rspack serve",
    "build": "rspack build"
  },
  "dependencies": {
    "@ant-design/icons-vue": "^6.1.0",
    "ant-design-vue": "^4.0.0",
    "axios": "^1.4.0",
    "crypto-js": "^4.1.1",
    "moment": "^2.29.4",
    "pinia": "^2.1.7",
    "pinia-plugin-persistedstate": "^3.2.0",
    "qs": "^6.11.2",
    "vue": "3.2.45",
    "vue-router": "^4.0.3",
    "vue3-draggable-resizable": "^1.6.5"
  },
  "devDependencies": {
    "@rspack/cli": "latest",
    "@types/crypto-js": "^4.1.2",
    "@types/node": "^20.8.7",
    "sass": "^1.32.7",
    "sass-loader": "^12.0.0",
    "vue-loader": "^17.2.2"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

**Comment by bvanjoi** [comment]
Could you provide the reduced repo where the issue was reproduced?

**Comment by JdesEva** [comment]
> Could you provide the reduced repo where the issue was reproduced?

https://github.com/JdesEva/rs-pack-demo

**Comment by bvanjoi** [comment]
reduced:

```json
// package.json
{
    "dependencies": {
         "pinia": "2.1.7",
         "vue": "3.2.45"
    }
}
```

```js
// index.js
import { getActivePinia } from "pinia";
getActivePinia()
```

This issue is not a bug induced by ﻿rspack. Similarly, webpack would also throw a comparable error during compilation:

<img width="599" alt="image" src="https://github.com/web-infra-dev/rspack/assets/30187863/89c3c98f-f960-40f5-99a5-b899c3271d80">

It seems appropriate to raise an issue for `﻿pinia` considering that ﻿`hasInjectionContext` is exposed from `﻿vue@>=3.3.0`: https://github.com/vuejs/core/blob/main/CHANGELOG.md#:~:text=)%20(869f3fb)-,hasInjectionContext()%20for%20libraries,-(%238111)%20(. Hence, ﻿`pinia` should specify ﻿`vue: >= 3.3.0` in their peer dependencies.

A similar question can be found: https://stackoverflow.com/questions/76294403/hasinjectioncontext-is-not-exported-by-node-modules-vue-demi-lib-index-mjs.

**Comment by JdesEva** [comment]
That's great! Thx
