### ISSUE TITLE
remove all @ts-expect-error 

### ISSUE THREAD

**Issue by hardfist** [web-infra-dev/rspack#4640]
https://github.com/web-infra-dev/rspack/pull/3863 introduces lots of //@ts-expect-error as workaround to enable typecheck test,
but  we should fix and remove all of it

**Comment by HerringtonDarkholme** [comment]
I would like to crush all the type errors in the code(call me TS error crusher). Would you like to assign this to me? 

There are pretty many of them so would you think that curating a list first would be a better approach? 

Thanks!

**Comment by hardfist** [comment]
> I would like to crush all the type errors in the code(call me TS error crusher). Would you like to assign this to me?
> 
> There are pretty many of them so would you think that curating a list first would be a better approach?
> 
> Thanks!

Yes, type gymnastics is back！

**Comment by HerringtonDarkholme** [comment]
Let me first recap the current status of ts-error usage in the repo.

# Overview
At the moment, more specifically eea9d067073930c350c5ad95f5c1ad89d6c6d424, rspack has 302 ts-expect-errors.

|Package Name| `ts-expect-error` Count|
|------|---------:|
|packages/rspack-cli|19|
|packages/rspack-dev-server|41|
|packages/rspack-plugin-html|18|
|packages/rspack-plugin-react-refresh|3|
|packages/rspack|211|
|scripts|1|
|webpack-test|9|

# Rspack core packages breakdown

Since rspack core packages itself has many ts-expect-error, a breakdown will be helpful to make every pull request change small and manageable.

|Package Name| `ts-expect-error` Count|
|------|---------:|
|src|53|
|src/builtin-loader|1|
|src/config|10|
|src/lib|29|
|src/loader-runner|25|
|src/logging|9|
|src/node|14|
|src/stats|18|
|src/util|50|
|test|2|

# Strategy
Type errors are nasty to see in codebase but should not impact runtime behavior.
To minimize the impact of fixing type error, changes will be split into small, standalone pull request and every change will aim at being type-level only.

**Comment by HerringtonDarkholme** [comment]
- [ ] packages/rspack-cli
- [ ] packages/rspack-dev-server 	41
packages/rspack-plugin-html 	18
packages/rspack-plugin-react-refresh 	3
packages/rspack 	211
scripts 	1
webpack-test

**Comment by hardfist** [comment]
Please  remember not modify any tsconfig during refactor, because it's easy to be broken like https://github.com/web-infra-dev/rspack/pull/4650

**Comment by HerringtonDarkholme** [comment]
bump

**Comment by hardfist** [comment]
@SoonIter is this finished?

**Comment by SoonIter** [comment]
> @SoonIter is this finished?

not all but most of them, there are still several parts

1. packages/rspack/loader-runner/index.js
2. packages/rspack/src/stats/DefaultStatsFactoryPlugin.ts
3. packages/rspack/src/MultiCompiler.ts
4. packages/rspack/src/Watching.ts
5. rspack-dev-server (cannot be removed because of private API)

and some one or two small pieces
