### ISSUE TITLE
[Bug]: webpack插件在rspack下引用，无法改变chunk的依赖关系，在webpack下可以

### ISSUE THREAD

**Issue by wengjiacheng** [web-infra-dev/rspack#5631]
### System Info

System:
    OS: macOS 13.3.1
    CPU: 2.5 GHz Intel Core i7
    Memory: 16 GB 2133 MHz LPDDR3
  Browsers:
    Chrome:  120.0.6099.109
  npmPackages:
    "@rsbuild/core": "^0.4.0",
    "@rsbuild/plugin-vue2": "^0.4.0",

### Details

有个需求是css文件过大需要拆分，原项目里使用的是css-split-webpack-plugin这个插件，这个插件给出的方法是支持webpack5, 我使用插件给的办法在webpack5中做了尝试也是可以正常打包的，
而且css文件的引入也是正常的
![image](https://github.com/web-infra-dev/rspack/assets/24770388/720e23e4-b810-4a7c-b0c1-78f72bacc605)
上面两个css引用在是他拆分后打包的结果

然后我在rsbuild构建的项目下也引用了这个插件
![image](https://github.com/web-infra-dev/rspack/assets/24770388/21f48e39-5623-453b-8519-9c4e962454f0)
这是我的配置，文件可以看到是打包出来了，但是并没有被引用
![image](https://github.com/web-infra-dev/rspack/assets/24770388/aef7a800-c95b-4acb-a8bf-e30337817745)
插件中修改文件的方式
![image](https://github.com/web-infra-dev/rspack/assets/24770388/8c01ba58-a842-4f9a-8aec-ccd320668203)
使用的钩子
processAssets

### Reproduce link

NONE

### Reproduce Steps

npm run build

**Comment by summer-boythink** [comment]
@wengjiacheng 我不知道这个plugin发生了什么，但我自己写了一个css split插件
https://github.com/summer-boythink/split-css-rspack-plugin

虽然目前支持的功能还不多，但您可以试一试

**Comment by wengjiacheng** [comment]
> summer-boythink
IE11对单个css文件有大小限制，单个css文件样式不能超过4096个，超过会自动截取，css-split-webpack-plugin可以对css文件大小限制，进行裁切，但是库本身只支持webpack4，之后就没有维护，在这个库的issue中有人给出了支持webpack5的方案，我在本地webpack5中尝试了，可以正常打包，裁切css,并且打包后chunk的依赖关系有没有变化。
然后就放在了rspack下进行尝试，可以打包出文件，但是没法影响chunk的依赖关系，打包出来的css文件插入不到需要的chunk中

**Comment by h-a-n-a** [comment]
`chunk` in readonly in rspack. We will improve the documentation. Thanks for the heads-up.

**Comment by wengjiacheng** [comment]
> `chunk` in readonly in rspack. We will improve the documentation. Thanks for the heads-up.

**Comment by wengjiacheng** [comment]
@xc2 请问这个问题有进展吗，有计划大概什么时候会解决吗？

**Comment by xc2** [comment]
@h-a-n-a could you pls tell if mutation support for chunk.files is planned

**Comment by h-a-n-a** [comment]
It's not planned to access internal structs like `Chunk`, `ModuleGraph`, etc on the JS side.

**Comment by Pablinho** [comment]
I'm trying to use this plugin: https://github.com/privatenumber/webpack-localize-assets-plugin , among other issues the one that seems more complex to solve is related to these lines:
for (const newAssetName of newAssetNames) {
	chunk.files.add(newAssetName);
} 
Which is updating the files for a chunk.

Example
Let's have a simple chunk with just one asset:
```
{
  id: '123',
  files: [ '123.[locale]-7bfd62f8b95f7904.mjs' ]
} 
```
Suppose we have locales for es, en, ja . After that function we might have something like:
```
{
  id: '123',
  files: [
    '123.en-332d176a9fbf2c40.mjs',
    '123.es-a59bd56cdc4bbfe9.mjs',
    '123.ja-a59bd56cdc4bbfe9.mjs',
  ]
}
```
So any other plugin that uses chunk.files  or chunkgraph.getFiles() would use the translated assets.

Now, related to rspack and its inability to update `chunk.files` on the **rust** side, currently I can't use the [rspack_plugin_banner](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_banner/src/lib.rs)  or [rspack_plugin_devtool](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs) for example because the use of chunk.files  ([here](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_banner/src/lib.rs#L198), and [here](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_plugin_devtool/src/source_map_dev_tool_plugin.rs#L514)). 

Also, I've notice that we deal with chunk.files when we rename_asset or delete_asset ([here](https://github.com/web-infra-dev/rspack/blob/main/crates/rspack_core/src/compiler/compilation.rs#L597-L622)) , but nothing when we emit_asset . Can we add an option to add chunk information when we emit an asset, (I mean. away to add assets to chunk.files)? Or do you think in other approach to solve this issue? Thanks is advance for any help on this matter.
