### ISSUE TITLE
[Feature]: CopyRspackPlugin 如何实现 copy-webpack-plugin 的 transform 方法

### ISSUE THREAD

**Issue by lucasllin** [web-infra-dev/rspack#5761]
### What problem does this feature solve?

目前CopyRspackPlugin没有支持transform方法，请问有相关的安排吗

### What does the proposed API of configuration look like?

type transform =
  | {
      transformer: (input: string, absoluteFilename: string) => string | Buffer;
      cache?: boolean | TransformerCacheObject | undefined;
    }
  | ((input: string, absoluteFilename: string) => string | Buffer);

**Comment by JSerFeng** [comment]
Because that's function type, previously we have lots of function type APIs not implemented, if you are willing to contribute, you can refer to a similar API, splitChunks.chunks here https://github.com/web-infra-dev/rspack/blob/c7024196b5f4f394d2294a093cbb52c3d200f848/crates/rspack_binding_options/src/options/raw_split_chunks/raw_split_chunk_chunks.rs#L23.
But using js function will slow down the build

**Comment by chenjiahan** [comment]
Supported in https://github.com/web-infra-dev/rspack/pull/6375
