### ISSUE TITLE
[Bug]: SWC Plugins doesn't work with builtin:swc-loader

### ISSUE THREAD

**Issue by rushi121** [web-infra-dev/rspack#5965]
### System Info

 System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 Intel(R) Xeon(R) W-2135 CPU @ 3.70GHz
    Memory: 35.34 GB / 63.73 GB
  Binaries:
    Node: 16.20.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.4 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Chrome: 122.0.6261.129
    Edge: Chromium (122.0.2365.80)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @rspack/cli: latest => 0.5.7
    @rspack/core: latest => 0.5.7

### Details

Rspack builtin:swc-loader gives parsing error when used with swc plugins.

### Reproduce link

https://github.com/rushi121/rspack-swc-plugin-builtin-loader-repro.git

### Reproduce Steps

Detailed steps are in repro repo readme

**Comment by chenjiahan** [comment]
the same as: https://github.com/web-infra-dev/rspack/issues/5921

**Comment by h-a-n-a** [comment]
Thanks for reporting this issue to us.
This happens if the plugin's SWC version not compatible with rspack's. There's an AST breaking change introduced in the latest version of swc. For SWC version in rspack 0.5.8, you may now use plugins of version 1.5.113. We would add some version checks to prevent this and guide user to use the corresponding version.

**Comment by h-a-n-a** [comment]
move to https://github.com/web-infra-dev/rspack/issues/5921

**Comment by rushi121** [comment]
Worked for me...thx
