### ISSUE TITLE
[Feature]: Support base64 hashDigest in builtin css modules localIdentName

### ISSUE THREAD

**Issue by daveskybet** [web-infra-dev/rspack#6031]
### What problem does this feature solve?

For users migrating existing projects across from Webpack css-loader that currently utilise the base64 hashDigest within the localIdentName for classname hashing (currently used as default and recommended values in the docs https://webpack.js.org/loaders/css-loader/#localidentname), this addition would remove the need to change hashing strategies in their projects.

### What does the proposed API of configuration look like?

```
builtins: {
    css: {
        modules: {
	    localIdentName: "[hash:base64]",
	},
    },
},
```
Would result in a valid hash.

**Comment by LingyuCoder** [comment]
Seems not be different with FilenameTemplate, the css-loader implements a special templated path [here](https://github.com/webpack-contrib/css-loader/blob/master/src/utils.js#L354-L373) cc @JSerFeng @SyMind

**Comment by SyMind** [comment]
@daveskybet We've decided not to implement this feature due to a couple of reasons:

1. Rspack is designed to be in alignment with webpack's `module.generator['css/module']` (experiments.css) functionality, which does not support the `localIdentName` format `[hash:base64]`.

2.Should you need to use the `[hash:base64]`, it's possible to do so by utilizing `css-loader` and `rspack.CssExtractRspackPlugin` to process your CSS files, with next Rspack version 0.6.0.

@ahabhgk cc

**Comment by daveskybet** [comment]
Thanks for the update @SyMind, disappointing but understandable. 

Do you by any chance have a rough ETA for version 0.6.0?

**Comment by JSerFeng** [comment]
>Do you by any chance have a rough ETA for version 0.6.0?

You should be able to try it within this week
