### ISSUE TITLE
[Bug]: Incorrect Javascript compilation

### ISSUE THREAD

**Issue by calinortan** [web-infra-dev/rspack#6124]
### System Info

  System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 93.39 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.1 - ~/.nvm/versions/node/v18.20.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.1/bin/npm
    bun: 1.0.1 - ~/.bun/bin/bun
  Browsers:
    Chrome: 123.0.6312.107
    Safari: 17.3
    Safari Technology Preview: 17.4
  npmPackages:
    @rspack/cli: latest => 0.5.9 
    @rspack/core: latest => 0.5.9 

### Details

hey guys ran into this issue after updating to rsbuild 0.4.11 (not reproducing on 0.4.10).

Basically this code logs `0` instead of `hello` how it should be.
```
const xhr = {
    responseType: "",
    responseText: "hello",
    response: "world",
  };

  const x =
    (xhr.responseType || "text") !== "text" || xhr.responseText !== "string"
      ? "hello"
      : "world";

  console.log(x);
```

This piece of code is what I found to be in the latest JQuery implementation, basically making all API requests done via $.ajax not work anymore.

You can see in the reproduce repository, that webpack version correctly logs 'hello'

### Reproduce link

https://github.com/calinortan/rspack-repro

### Reproduce Steps

yarn
yarn dev:rspack - to see rspack version
yarn dev:webpack - to see webpack version

**Comment by LingyuCoder** [comment]
caused by compile time evaluation

original code: 
```js
const xhr = {
    responseType: "",
    responseText: "hello",
    response: "world",
  };

  const x =
    (xhr.responseType || "text") !== "text" || xhr.responseText !== "string"
      ? "hello"
      : "world";
```

after compile time evaluation:
```js
const xhr = {
      responseType: "",
      responseText: "hello",
      response: "world"
  };
  const x = (xhr.responseType || "text") !== "text" || 0 ? "hello" : 0;
```

the result of [expression.as_bool()](https://github.com/web-infra-dev/rspack/blob/27115fafea62b7a32f5ab1bcf97308c605138a79/crates/rspack_plugin_javascript/src/parser_plugin/const/logic_expr.rs#L18) is true, it is different [webpack](https://github.com/web-infra-dev/rspack/blob/27115fafea62b7a32f5ab1bcf97308c605138a79/crates/rspack_plugin_javascript/src/parser_plugin/const/logic_expr.rs#L18) which is `undefined`.

cc @bvanjoi @ahabhgk
