### ISSUE TITLE
[Bug]: Bundle Analyzer issue

### ISSUE THREAD

**Issue by elsassph** [web-infra-dev/rspack#6737]
### System Info

```
System:
    OS: macOS 14.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 259.19 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.21 - ~/.nvm/versions/node/v18.16.1/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
    pnpm: 8.15.6 - ~/.nvm/versions/node/v18.16.1/bin/pnpm
    bun: 1.0.15 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.142
    Safari: 17.5
  npmPackages:
    @rspack/cli: ^0.7.1 => 0.7.1 
    @rspack/core: ^0.7.1 => 0.7.1 
```

### Details

When updating from 0.6.x to 0.7.x the analyzer report regressed to show a partial view of the modules (size is mostly identical).

Right: 0.6.3, left: 0.7.1
![image](https://github.com/web-infra-dev/rspack/assets/297963/e7d2bb07-4e78-4b61-adce-68ce45edae1c)

Some specifics of the configuration:
- `concatenateModules: true`
- `externalHelpers: true`

### Reproduce link

https://github.com/elsassph/test-rspack-compat

### Reproduce Steps

```
npx rspack --analyze
```

**Comment by LingyuCoder** [comment]
Unable to run your repro. There is no rule for jsx files in rspack.config.js. However, there are jsx files inside `@lightningjs/solid/dist/source/components`.

**Comment by elsassph** [comment]
@LingyuCoder thanks for checking - I indeed had a patched `@lightningjs/solid` library so I pushed a change to ignore that for now (BTW the nasty "panic" error still happens with a JSX handler). The issue reported now appears with a clean checkout.

**Comment by LingyuCoder** [comment]
> @LingyuCoder thanks for checking - I indeed had a patched `@lightningjs/solid` library so I pushed a change to ignore that for now (BTW the nasty "panic" error still happens with a JSX rule). The issue reported now appears with a clean checkout.

Panic should has been fixed by https://github.com/web-infra-dev/rspack/pull/6778. 

In your repro, webpack uses ts-loader and rspack uses builtin:swc-loader. Helpers of swc-loader are required as commonjs modules so that they can not be full concatenated. Use swc-loader in webpack is just the same.

But rspack does not support `nestedModules` and `depth` in stats, which is used to drill-down analysis of concatenated modules. I will add them in https://github.com/web-infra-dev/rspack/pull/6784.

**Comment by elsassph** [comment]
@LingyuCoder the screenshot was comparing only Rspack, you can ignore the Webpack configuration - sorry if this is causing confusion. The issue is that bundle analizer report has "regressed" between 0.6.x and 0.7.x

**Comment by LingyuCoder** [comment]
> @LingyuCoder the screenshot was comparing only Rspack versions, you can ignore the Webpack configuration - sorry if this is causing confusion. The issue is that bundle analizer report has "regressed" between 0.6.x and 0.7.x.

In rspack 0.6.x, all module were wrapped in __webpack_modules__ so that webpack-bundler-analyzer can easily parse the bundle artifact and get modules.

Rspack 0.7.x extract the entry module into bootstrap, which aligned with webpack, and then the bundle analyzer can not parse it without module.depth (0 means entry module). And also, lots of modules are concatenated into entry module, so they are lost in parsed viewer.

**Comment by elsassph** [comment]
Thanks, does that mean that we need to specify a stats module depth in the rspack config? or will that "just work" now?

**Comment by LingyuCoder** [comment]
Yes, the stats module depth has been supported by https://github.com/web-infra-dev/rspack/pull/6784. I test your repro and `rspack --analyze` works well. You can wait for the latest nightly version, and we will release it later today.

**Comment by elsassph** [comment]
Cool, no urgency.
