### ISSUE TITLE
[Feature]: Could you help to upgrade the built-in SWC loader to use the latest version of SWC?

### ISSUE THREAD

**Issue by cjnoname** [web-infra-dev/rspack#7613]
### What problem does this feature solve?

SWC has fixed a few bugs on their side, but it seems like RSpack is using an outdated version of SWC.
Please upgrade the SWC to the latest version to take advantage of all the new features and bug fixes.

### What does the proposed API of configuration look like?
Is it possible to make @swc/core a peer dependency so that people can easily upgrade it?

**Comment by h-a-n-a** [comment]
> Is it possible to make @swc/core a peer dependency so that people can easily upgrade it?

It's not. The architecture of `rspack_core` is different from simply dragging a specific `@swc/core` for JS Loader. 

Under the hood of rspack, swc is deeply integrated into the rspack at link time. This means it's Wasm plugin execution and the behavior of compiler are also bound to the integrated version of the linked swc. This cannot be changed during its runtime.

However for `swc-loader`, of which it's swc binary is a standalone JS binding, can be easily switched to the other one.

> Please upgrade the SWC to the latest version to take advantage of all the new features and bug fixes.

PRs are also welcome. But note: beyond rspack version 1.0, if there's a breaking change in SWC AST and because SWC AST breaking changes might affect Wasm plugin users, we will only publish these changes in minor versions.

**Comment by cjnoname** [comment]
> > Is it possible to make @swc/core a peer dependency so that people can easily upgrade it?
> 
> It's not. The architecture of `rspack_core` and it's builtin loader are different from simply swap-in a specific `@swc/core` as it does when paring with a JS swc-loader.
> 
> Under the hood of rspack, swc is deeply integrated into the rspack at link time. This means its Wasm plugin execution and the behavior of compiler are also bound to the integrated version of the linked swc. This cannot be changed during its runtime.
> 
> However for `swc-loader`, of which it's swc binary is a standalone JS binding, can be easily switched to one another.
> 
> > Please upgrade the SWC to the latest version to take advantage of all the new features and bug fixes.
> 
> PRs are also welcome. But note: beyond rspack version 1.0, if there's a breaking change in SWC AST and because SWC AST breaking changes might affect Wasm plugin users, we will only publish these changes in minor versions.

Sorry, I didn't explain that clearly. Does this mean I can upgrade the @swc/core version within builtin:swc-loader, or do I need to switch from builtin:swc-loader to a standard swc-loader to access the latest SWC version?

**Comment by h-a-n-a** [comment]
> Does this mean I can upgrade the @swc/core version within builtin:swc-loader, or do I need to switch from builtin:swc-loader to a standard swc-loader to access the latest SWC version?

You have to use `swc-loader` (not builtin) to use npm package @swc/core, i.e accessing to your desired SWC version.

**Comment by cjnoname** [comment]
> > Does this mean I can upgrade the @swc/core version within builtin:swc-loader, or do I need to switch from builtin:swc-loader to a standard swc-loader to access the latest SWC version?
> 
> You have to use `swc-loader` (not builtin) to use npm package @swc/core, i.e accessing to your desired SWC version.

Thanks! "swc-load" works like a charm.

Cheers.
