### ISSUE TITLE
[Bug]: Failed to load module script: Expected a JavaScript module script

### ISSUE THREAD

**Issue by xcxiao7710** [web-infra-dev/rspack#8224]
### System Info

Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
![Image](https://github.com/user-attachments/assets/b6950511-a341-4b93-aa9c-040fcd6d2f62)

### Details

![Image](https://github.com/user-attachments/assets/f66c3170-a8d8-44ae-b0bd-bb740da43b92)
What is the reason for this problem after packaging and deploying?
Do we still need to configure something else?

### Reproduce link

https://mozilla.github.io/pdf.js/getting_started/#download

### Reproduce Steps

https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by LingyuCoder** [comment]
Not sure how you import the pdf.js, can you provide a complete repro?

**Comment by xcxiao7710** [comment]
https://mozilla.github.io/pdf.js/getting_started/#download
Downloaded to public/web, but encountered issues during deployment after packaging

**Comment by LingyuCoder** [comment]
I can not understand what the problem is. If the assets has been deployed to your own server, you should check whether the header of the file on your server meets the expectations.

Or are you means that you are using `rspack serve` to start a local server and copy the `pdf.js` the dist folder, and then try to access it in your browser?
