### ISSUE TITLE
[Bug]: the built-in ejs syntax of the HtmlRspackPlugin is inconsistent with the syntax of ejs itself

### ISSUE THREAD

**Issue by iDestin** [web-infra-dev/rspack#8393]
### System Info

```
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M3
    Memory: 248.86 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    pnpm: 7.33.7 - ~/.nvm/versions/node/v16.16.0/bin/pnpm
  Browsers:
    Chrome: 130.0.6723.117
    Safari: 17.4
```

### Details

`<%-` is escaped in `HtmlRspackPlugin` , but not in ejs , This makes it impossible to use both simultaneously

**rspack doc**
[rspack](https://rspack.dev/zh/plugins/rspack/html-rspack-plugin#%E7%94%A8%E6%B3%95)
![Image](https://github.com/user-attachments/assets/8890d5af-aea1-4ba7-a0c2-e0c224c0a9c1)

**ejs doc**
[ejs](https://ejs.bootcss.com/#install)
![Image](https://github.com/user-attachments/assets/587234be-fb5f-4a36-a09c-7c1976df3f75)

The expectation is that the two are consistent

### Reproduce link

https://rspack.dev/zh/plugins/rspack/html-rspack-plugin#%E7%94%A8%E6%B3%95

### Reproduce Steps

No need to reproduce

**Comment by hardfist** [comment]
this is by design and documented here  
![Image](https://github.com/user-attachments/assets/7646fb03-031c-412f-a0bc-7a15cca559d5)
since ejs support custom the interop syntax you can still make it work together
https://github.com/mde/ejs#:~:text=escape%20The%20escaping%20function%20used%20with%20%3C%25%3D%20construct.%20It%20is%20used%20in%20rendering%20and%20is%20.toString()ed%20in%20the%20generation%20of%20client%20functions.%20(By%20default%20escapes%20XML).

**Comment by iDestin** [comment]
> https://github.com/mde/ejs#:~:text=escape%20The%20escaping%20function%20used%20with%20%3C%25%3D%20construct.%20It%20is%20used%20in%20rendering%20and%20is%20.toString()ed%20in%20the%20generation%20of%20client%20functions.%20(By%20default%20escapes%20XML)

ok！I'll try, thank you
