### ISSUE TITLE
[Bug]: "No code generation entry" panic when using lazy compilation

### ISSUE THREAD

**Issue by chenjiahan** [web-infra-dev/rspack#8861]
### System Info

  System:
    OS: macOS 14.6.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 3.86 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.9.0 - ~/Library/Caches/fnm_multishells/86843_1735183914921/bin/node
    npm: 10.8.3 - ~/Library/Caches/fnm_multishells/86843_1735183914921/bin/npm
    pnpm: 9.15.1 - ~/Library/Caches/fnm_multishells/86843_1735183914921/bin/pnpm
    bun: 1.1.34 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.205
    Safari: 17.6
  npmPackages:
    rspress: 1.39.2 => 1.39.2

### Details

The Rspack website panics when using lazy compilation:

![Image](https://github.com/user-attachments/assets/e69bd36d-049c-4011-8e17-238c5362fb89)

### Reproduce link

https://github.com/web-infra-dev/rspack/tree/main/website

commitId: 3f2a390a880aa7b3f26bac1a319cdb609012022a

### Reproduce Steps

1. cd website
2. pnpm run dev
3. click some nav items:

![Image](https://github.com/user-attachments/assets/4e9e268d-16a3-415d-b82b-7faa1197413e)

**Comment by JSerFeng** [comment]
The reason is that when doing HMR with all incremental passes enabled, codegen only happens for modules that have changes.

This is fine in most cases, however if one module is removed by tree shaking in the initial build, but is active in the second build, codegen phase assume it has already been rendered in the initial build.

We've fixed detection strategy in #8871
